[project]
name = "ardent-comfyui"
description = "FilenamePrefix By Date, ..."
version = "0.1.9"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/ardentillumina/ardent-comfy"

[tool.comfy]
PublisherId = "ardentillumina"
DisplayName = "Ardent Nodes"
